PRESS4-274-WooCommerce has been successfully installed alert is persistent
newfold-labs/wp-module-ecommerce pull request #102
Opened 2023-07-07 09:14 UTC by sumathi3399

JIRA Link:- https://jira.newfold.com/browse/PRESS4-274

- For the woocommerce success installation notification  `5 seconds` duration has been added, So that it will disappear after specified time.

2023-07-07 09:17 UTC, aulisius requested changes

2023-07-07 09:17 UTC, aulisius commented on src/components/useInstallWoo.js
> +        autoDismiss: "5000"
This should be a number

2023-07-07 18:28 UTC, sumathi3399 commented on src/components/useInstallWoo.js
> +        autoDismiss: "5000"
made the changes

2023-07-08 00:12 UTC, aulisius approved these changes

2023-07-08 00:12 UTC, merged