Removing learn more based on hostgatro brand
newfold-labs/wp-module-ecommerce pull request #124
Opened 2023-09-04 12:34 UTC by ramyakrishnai

from bluehost
<img width="1728" alt="Screenshot 2023-09-04 at 6 01 41 PM" src="https://github.com/newfold-labs/wp-module-ecommerce/assets/80672694/725f9512-d211-4ac7-981a-5185ff22966e">

from hostgator
<img width="1728" alt="Screenshot 2023-09-04 at 6 01 18 PM" src="https://github.com/newfold-labs/wp-module-ecommerce/assets/80672694/9d5f93bc-207e-471a-8895-a3dc65f3c623">

2023-09-06 14:09 UTC, aulisius requested changes

2023-09-06 14:09 UTC, aulisius commented on includes/Data/Brands.php
> +						'woocommerce_default_country' => 'US:AZ',
Are we sure these values are correct for Hostgator?

2023-09-06 14:09 UTC, aulisius commented on includes/Data/Brands.php
> +						'payment' => array('Paypal', 'Razorpay'),
Do we need Razorpay for HG?

2023-09-06 14:09 UTC, aulisius commented on src/configs/selectors.js
> +export const yithOnboardingPaymentParser = (titles) => (data) => {
Can be simplified as 
```js
let isCompleted = titles.some(key => data?.[key] === "true");
```

2023-09-07 10:21 UTC, ramyakrishnai commented on includes/Data/Brands.php
> +						'payment' => array('Paypal', 'Razorpay'),
yes, we need both

2023-09-07 14:32 UTC, aratidgr8 approved these changes

2023-09-07 14:43 UTC, aulisius approved these changes

2023-09-07 14:43 UTC, merged